# file: homelab/ansible/roles/hostsfile/tasks/main.yml
#   - update the /etc/hosts file on the nodes
#  

- name: Update /etc/hosts file
  block:
    - name: update /etc/hosts file on the node
      copy:
        src: hosts
        dest: /etc/hosts
      
  become: true
  become_user: root