# file: homelab/roles/nfs-client/tasks/main.yml
#   playbook for setting up nfs-client 
#  
- name: Install nfs-client daemon!
  block:
    - name: Install nfs-client via apt
      apt:
        pkg:
          - nfs-client

    - name: Create homelab NFS share location on filesystem
      file:
        path: /nfs/nas
        state:  directory

    - name: Mount NFS volume from NAS
      mount:
        src: 192.168.7.74:/volume3/docker
        path: /nfs/nas
        opts: auto
        state: mounted
        fstype: nfs
        
  become: true
  become_user: root