# file: homelab/roles/sysmods/tasks/main.yml
#   playbook for setting up system mods for kubernetes and containerd 
#  

- name: configure kernel module loading for containerd
  copy:
    src: containerd.conf
    dest: /etc/modules-load.d/containerd.conf
  become: true
  become_user: root
  register: CONTAINERD_CONFIG


- name: load kernel modules for containerd for use now (overlay)
  community.general.modprobe:
    name: overlay
    state: present

- name: load kernel modules for containerd for use now (br_netfilter)
  community.general.modprobe:
    name: br_netfilter
    state: present


- name: modify sysctl for iptables bridge and ip forwarding
  copy:
    src: 99-kubernetes-cri.conf
    dest: /etc/sysctl.d/99-kubernetes-cri.conf
  become: true
  become_user: root
  register: SYSCTL_IP_FORWARD


- name: apply system mods via sysctl (without rebooting system)
  when: SYSCTL_IP_FORWARD is changed
  sysctl:
    reload: yes


- name: restart containerd to pickup changes
  when: CONTAINERD_CONFIG is changed
  systemd:
    name: containerd
    state: restarted