raspberrypi:
  hosts:
    rpi01:
      ansible_host:	192.168.7.140  # hostname: charon
    rpi02:
      ansible_host:	192.168.7.141  # hostname: nix
    rpi03:
      ansible_host:	192.168.7.142  # hostname: hydra
    rpi04:
      ansible_host:	192.168.7.143  # hostname: styx
    rpi05:
      ansible_host:	192.168.7.144  # hostname: kerberos
  vars:
    ansible_user: ubuntu
    ansible_ssh_private_key_file: "~/.ssh/ansible_master"

synology:
  hosts:
    nas01:
      ansible_host: 

homelab:
  children:
    raspberrypi:
    synology: