# file: homelab/roles/groups/tasks/main.yml
#   playbook for setting up cgroups for k8s
#   
- name: Modify /boot/firmware/cmdline.txt to enable cgroups for microk8s
  ansible.builtin.lineinfile:
    path: /boot/firmware/cmdline.txt
    state: present
    regexp: '^net\.ifnames=0'
    line: 'cgroup_enable=memory cgroup_memory=1 net.ifnames=0 dwc_otg.lpm_enable=0 console=serial0,115200 console=tty1 root=LABEL=writable rootfstype=ext4 elevator=deadline rootwait fixrtc'
  become: true
  become_user: root