# file: homelab/roles/calicoctl/tasks/main.yml
#   playbook for setting up calico controller app (calicoctl) 
#  

- name: Install Calico Controller App on k8s nodes"
  block:
    - name: copy the calicoctl app to node
      copy:
        src: calicoctl
        dest: /usr/local/bin/calicoctl
  become: true
  become_user: root