# file: homelab/roles/calicoctl/tasks/main.yml
#   Calico Controller
#   - installs calicoctl and symlinks to calicoctl- 
#  

- name: Install Calico Controller App on k8s nodes"
  block:
    - name: setup calicoctl for ARM linux (64-bit)
      get_url:
        url: https://github.com/projectcalico/calicoctl/releases/download/v3.19.0/calicoctl-linux-arm64
        dest: /usr/local/bin/calicoctl
        mode: '0755'
      when: ansible_facts['architecture'] == 'aarch64' and ansible_facts['system'] == 'Linux'

    - name: setup calicoctl for x86_64 linux (64-bit)
      get_url:
        url: https://github.com/projectcalico/calicoctl/releases/download/v3.19.0/calicoctl
        dest: /usr/local/bin/calicoctl
        mode: '0755'
      when: ansible_facts['architecture'] == 'x86_64' and ansible_facts['system'] == 'Linux'

    - name: create symlink to enable kubectl-calico
      file:
        src: /usr/local/bin/calicoctl
        dest: /usr/local/bin/kubectl-calico
        owner: root
        group: root
        state: link    
  become: true
  become_user: root